
steps:
  #build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/gcp-praticals/artifactnewrep/web:latest'
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-central1-docker.pkg.dev/gcp-praticals/artifactnewrep/web:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - run
      - deploy
      - 'web-deploy' 
      - '--image'
      - 'us-central1-docker.pkg.dev/gcp-praticals/artifactnewrep/web:latest'
      - '--region'
      - 'us-central1' 
      - '--platform'
      - 'managed'
options:
  logging: CLOUD_LOGGING_ONLY
