apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: demo-1-target-11
profiles:
- name: dev
  manifests:
    rawYaml:
    - cloud-deploy/demo-1-target-11/dev/dev.yaml
#- name: prod
 # manifests:
  #  rawYaml:
   # - cloud-deploy/marvel/prod/prod.yaml
deploy:
  cloudrun: {}
